#include <stdio.h>
#include <stdlib.h>
#include <string.h>
//Global Vars
//Read = 1 Write = 0

int mainMemorySize, cacheSize, blockSize;
char replacementPolicy, fileName[];
typedef struct cpu_Output{
	int readWrite;
	int address;
} cpuOutput;

int main() {
	runStartUp();

}

void runStartUp(){
	printf("Enter the size of main memory in bytes: ");
	scanf(" %d", &mainMemorySize);
	printf("Enter the size of the cache in bytes: ");
	scanf(" %d", &cacheSize);
	printf("Enter the cache line/block size: ");
	scanf(" %d", &blockSize);
	printf("Enter the replacement policy (L = LRU, F = FIFO): ");
	scanf(" %c", &replacementPolicy);
	printf("Enter the name of the input file containing the list of memory references generated by the CPU: ");
	scanf(" %s", fileName);
}

cpuOutput * readFile(char * fileName){
	FILE *fp = fopen(fileName, "r");
	char rW[1], addr[5], refTotal[12];
	int references;
	fscanf(fp, "%s", refTotal);
	references = atoi(refTotal);
	cpuOutput * cpuFile;
	cpuFile = malloc (references * sizeof(cpuFile));
	int readArray[references][2];
	for (int i=0; i<references; i++){
		fscanf(fp, "%s", rW);
		if (rW == "R") cpuFile[i].readWrite = 1;
		else readArray[i][0] = 0;
		fscanf(fp, "%s", addr);
		cpuFile[i].address = atoi(addr);
	}
	return cpuFile;
}